### ISSUE TITLE
Example does not work on cockroachdb

### ISSUE THREAD

**Issue by RemiKalbe** [SeaQL/sea-query#81]
Hello,

Do you plan on supporting CockroachDB?
Currently, running the Postgres example result in the following error

```
Create table character: ()

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: None, code: SqlState(E42601), message: "error in argument for $2: int8 requires 8 bytes for binary format", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("encoding.go"), line: Some(520), routine: Some("DecodeDatum") }) }', examples/postgres/src/main.rs:48:67
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/result.rs:1355:5
   3: core::result::Result<T,E>::unwrap
             at /Users/remikalbe/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:1037:23
   4: sea_query_postgres_example::main
             at ./src/main.rs:48:15
   5: core::ops::function::FnOnce::call_once
             at /Users/remikalbe/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by tyt2y3** [comment]
https://www.cockroachlabs.com/docs/stable/int.html
![image](https://user-images.githubusercontent.com/1782664/127770070-f58a15d9-04d2-44c6-af40-9be90a47659f.png)

You have to change all 32 bit integers to 64 bit ones.

But strictly speaking, it should not be a problem though, because CockroachDB 'should be' syntax compatible with Postgres. So the problems are only how we drive the queries.

**Comment by RemiKalbe** [comment]
I changed 

```rust
struct CharacterStruct {
    id: i32,
    character: String,
    font_size: i32,
}
```
to
```rust
struct CharacterStruct {
    id: i64,
    character: String,
    font_size: i64,
}
```
and
```rust
let id: i32 = row.try_get(0).unwrap();
```
to
```rust
let id: i64 = row.try_get(0).unwrap();
```

But I'm still getting the same error, so I tried changing:
```rust
.integer()
```
to
```rust
.big_integer()
```
still the same error.
Did I forget something?

**Comment by billy1624** [comment]
Hi @RemiKalbe, so after all these changes. You still got the same error?

**Comment by tyt2y3** [comment]
I believe the literals have to be changed to 64 bit too, e.g. `12u64`

**Comment by RemiKalbe** [comment]
Indeed, changing the literals make it work. I also tried the JSON example, and it also works. Thank you 😄

**Comment by tyt2y3** [comment]
Great. If you don't mind, perhaps you can publish your fork? May be we can add it to our examples!

**Comment by RemiKalbe** [comment]
No problem, I'll open a PR.
